# Generated by Django 5.2.7 on 2025-10-23 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_availabilityslot_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityslot",
            name="end_time",
            field=models.TimeField(
                choices=[
                    (datetime.time(8, 0), "08:00 AM"),
                    (datetime.time(8, 30), "08:30 AM"),
                    (datetime.time(9, 0), "09:00 AM"),
                    (datetime.time(9, 30), "09:30 AM"),
                    (datetime.time(10, 0), "10:00 AM"),
                    (datetime.time(10, 30), "10:30 AM"),
                    (datetime.time(11, 0), "11:00 AM"),
                    (datetime.time(11, 30), "11:30 AM"),
                    (datetime.time(12, 0), "12:00 PM"),
                    (datetime.time(12, 30), "12:30 PM"),
                    (datetime.time(13, 0), "01:00 PM"),
                    (datetime.time(13, 30), "01:30 PM"),
                    (datetime.time(14, 0), "02:00 PM"),
                    (datetime.time(14, 30), "02:30 PM"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="availabilityslot",
            name="start_time",
            field=models.TimeField(
                choices=[
                    (datetime.time(8, 0), "08:00 AM"),
                    (datetime.time(8, 30), "08:30 AM"),
                    (datetime.time(9, 0), "09:00 AM"),
                    (datetime.time(9, 30), "09:30 AM"),
                    (datetime.time(10, 0), "10:00 AM"),
                    (datetime.time(10, 30), "10:30 AM"),
                    (datetime.time(11, 0), "11:00 AM"),
                    (datetime.time(11, 30), "11:30 AM"),
                    (datetime.time(12, 0), "12:00 PM"),
                    (datetime.time(12, 30), "12:30 PM"),
                    (datetime.time(13, 0), "01:00 PM"),
                    (datetime.time(13, 30), "01:30 PM"),
                    (datetime.time(14, 0), "02:00 PM"),
                    (datetime.time(14, 30), "02:30 PM"),
                ]
            ),
        ),
    ]
